<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA21cuMX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA21cuMX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA21cuMX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA21cuMX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA21cuMX\App_KernelDevDebugContainer([
    'container.build_hash' => 'A21cuMX',
    'container.build_id' => '7a03621a',
    'container.build_time' => 1607523562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA21cuMX');
